window.UES_GUIDE_MANIFEST = {
  structures: [
    {
      id: 'hidden',
      title: 'Hidden',
      children: [
        { title: 'Interactive Visualizations', path: 'source/hidden/interactive-visualizations/interactive-visualizations.md' },
      ],
    },
    {
      id: 'math',
      title: 'Math',
      children: [
        { title: 'Arithmetic', path: 'source/math/arithmetic/arithmetic.md' },
        { title: 'Logic', path: 'source/math/logic/logic.md' },
        { title: 'Geometry', path: 'source/math/geometry/geometry.md' },
        { title: 'Algebra', path: 'source/math/algebra/algebra.md' },
        { title: 'Functions', path: 'source/math/functions/functions.md' },
        { title: 'Probability', path: 'source/math/probability/probability.md' },
        { title: 'Statistics', path: 'source/math/statistics/statistics.md' },
        { title: 'Trigonometry', path: 'source/math/trigonometry/trigonometry.md' },
        { title: 'Limits', path: 'source/math/limits/limits.md' },
        { title: 'Derivatives', path: 'source/math/derivatives/derivatives.md' },
        { title: 'Integrals', path: 'source/math/integrals/integrals.md' },
        { title: 'Series', path: 'source/math/series/series.md' },
        { title: 'Vectors', path: 'source/math/vectors/vectors.md' },
        { title: 'Matrices', path: 'source/math/matrices/matrices.md' },
        { title: 'Eigenvalues', path: 'source/math/eigenvalues/eigenvalues.md' },
        { title: 'Discrete Math', path: 'source/math/discrete-math/discrete-math.md' },
        { title: 'Modeling', path: 'source/math/modeling/modeling.md' },
        { title: 'First Order ODEs', path: 'source/math/first-order-odes/first-order-odes.md' },
        { title: 'Second Order ODEs', path: 'source/math/second-order-odes/second-order-odes.md' },
        { title: 'Systems of ODEs', path: 'source/math/systems-of-odes/systems-of-odes.md' },
        { title: 'Proof Writing', path: 'source/math/proof-writing/proof-writing.md' },
      ],
    },
    {
      id: 'physics',
      title: 'Physics',
      children: [
        { title: 'Thermodynamics I', path: 'source/physics/thermodynamics-i/thermodynamics-i.md' },
        { title: 'Physics I', path: 'source/physics/physics-i/physics-i.md' },
        { title: 'Physics II', path: 'source/physics/physics-ii/physics-ii.md' },
        { title: 'Quantum Physics I', path: 'source/physics/quantum-physics-i/quantum-physics-i.md' },
        { title: 'Classical Mechanics', path: 'source/physics/classical-mechanics/classical-mechanics.md' },
        { title: 'Electricity and Magnetism', path: 'source/physics/electricity-and-magnetism/electricity-and-magnetism.md' },
        { title: 'Relativity', path: 'source/physics/relativity/relativity.md' },
        { title: 'Optics', path: 'source/physics/optics/optics.md' },
        { title: 'General Chemistry', path: 'source/physics/general-chemistry/general-chemistry.md' },
        { title: 'Organic Chemistry', path: 'source/physics/organic-chemistry/organic-chemistry.md' },
      ],
    },
    {
      id: 'engineering',
      title: 'Engineering',
      children: [
        { title: 'Statics', path: 'source/engineering/statics/statics.md' },
        { title: 'Dynamics', path: 'source/engineering/dynamics/dynamics.md' },
        { title: 'Mechanics of Materials', path: 'source/engineering/mechanics-of-materials/mechanics-of-materials.md' },
        { title: 'Fluid Mechanics', path: 'source/engineering/fluid-mechanics/fluid-mechanics.md' },
        { title: 'Heat Transfer', path: 'source/engineering/heat-transfer/heat-transfer.md' },
        { title: 'Materials Science', path: 'source/engineering/materials-science/materials-science.md' },
        { title: 'Electrical Circuit Analysis', path: 'source/engineering/electrical-circuit-analysis/electrical-circuit-analysis.md' },
        { title: 'Linear System Signal Analysis', path: 'source/engineering/linear-system-signal-analysis/linear-system-signal-analysis.md' },
        { title: 'Engineering Design', path: 'source/engineering/engineering-design/engineering-design.md' },
      ],
    },
  ],
};
