window.UES_GUIDE_MANIFEST = {
  structures: [
    {
      id: 'general',
      title: 'General',
      children: [
        { title: 'Introduction', path: 'subjects/general/introduction/introduction.md' },
        { title: 'Adding and Editing Documents', path: 'subjects/general/adding-and-editing-documents/adding-and-editing-documents.md' },
      ],
    },
    {
      id: 'math',
      title: 'Math',
      children: [
        { title: 'Arithmetic', path: 'subjects/math/arithmetic/arithmetic.md' },
        { title: 'Logic', path: 'subjects/math/logic/logic.md' },
        { title: 'Geometry', path: 'subjects/math/geometry/geometry.md' },
        { title: 'Algebra', path: 'subjects/math/algebra/algebra.md' },
        { title: 'Functions', path: 'subjects/math/functions/functions.md' },
        { title: 'Probability', path: 'subjects/math/probability/probability.md' },
        { title: 'Statistics', path: 'subjects/math/statistics/statistics.md' },
        { title: 'Trigonometry', path: 'subjects/math/trigonometry/trigonometry.md' },
        { title: 'Limits', path: 'subjects/math/limits/limits.md' },
        { title: 'Derivatives', path: 'subjects/math/derivatives/derivatives.md' },
        { title: 'Integrals', path: 'subjects/math/integrals/integrals.md' },
        { title: 'Series', path: 'subjects/math/series/series.md' },
        { title: 'Vectors', path: 'subjects/math/vectors/vectors.md' },
        { title: 'Matrices', path: 'subjects/math/matrices/matrices.md' },
        { title: 'Eigenvalues', path: 'subjects/math/eigenvalues/eigenvalues.md' },
        { title: 'Discrete Math', path: 'subjects/math/discrete-math/discrete-math.md' },
        { title: 'Modeling', path: 'subjects/math/modeling/modeling.md' },
        { title: 'First Order ODEs', path: 'subjects/math/first-order-odes/first-order-odes.md' },
        { title: 'Second Order ODEs', path: 'subjects/math/second-order-odes/second-order-odes.md' },
        { title: 'Systems of ODEs', path: 'subjects/math/systems-of-odes/systems-of-odes.md' },
        { title: 'Proof Writing', path: 'subjects/math/proof-writing/proof-writing.md' },
      ],
    },
    {
      id: 'physics',
      title: 'Physics',
      children: [
        { title: 'Thermodynamics I', path: 'subjects/physics/thermodynamics-i/thermodynamics-i.md' },
        { title: 'Physics I', path: 'subjects/physics/physics-i/physics-i.md' },
        { title: 'Physics II', path: 'subjects/physics/physics-ii/physics-ii.md' },
        { title: 'Quantum Physics I', path: 'subjects/physics/quantum-physics-i/quantum-physics-i.md' },
        { title: 'Classical Mechanics', path: 'subjects/physics/classical-mechanics/classical-mechanics.md' },
        { title: 'Electricity and Magnetism', path: 'subjects/physics/electricity-and-magnetism/electricity-and-magnetism.md' },
        { title: 'Relativity', path: 'subjects/physics/relativity/relativity.md' },
        { title: 'Optics', path: 'subjects/physics/optics/optics.md' },
        { title: 'Computational Physics', path: 'subjects/physics/computational-physics/computational-physics.md' },
        { title: 'Lab and Measurement', path: 'subjects/physics/lab-and-measurement/lab-and-measurement.md' },
        { title: 'Astrophysics and Cosmology', path: 'subjects/physics/astrophysics-and-cosmology/astrophysics-and-cosmology.md' },
        { title: 'Biophysics', path: 'subjects/physics/biophysics/biophysics.md' },
        { title: 'Condensed Matter Physics', path: 'subjects/physics/condensed-matter-physics/condensed-matter-physics.md' },
        { title: 'Geophysics', path: 'subjects/physics/geophysics/geophysics.md' },
        { title: 'Particle and Nuclear Physics', path: 'subjects/physics/particle-and-nuclear-physics/particle-and-nuclear-physics.md' },
        { title: 'Plasma Physics', path: 'subjects/physics/plasma-physics/plasma-physics.md' },
      ],
    },
    // {
    //   id: 'data-computing',
    //   title: 'Data / Computing',
    //   children: [
    //     { title: 'Programming', path: 'subjects/data-computing/programming/programming.md' },
    //     { title: 'Data Structures', path: 'subjects/data-computing/data-structures/data-structures.md' },
    //     { title: 'Algorithms', path: 'subjects/data-computing/algorithms/algorithms.md' },
    //     { title: 'Databases', path: 'subjects/data-computing/databases/databases.md' },
    //     { title: 'Software Design', path: 'subjects/data-computing/software-design/software-design.md' },
    //     { title: 'Version Control', path: 'subjects/data-computing/version-control/version-control.md' },
    //     { title: 'Operating Systems', path: 'subjects/data-computing/operating-systems/operating-systems.md' },
    //     { title: 'Computer Architecture', path: 'subjects/data-computing/computer-architecture/computer-architecture.md' },
    //     { title: 'Networking', path: 'subjects/data-computing/networking/networking.md' },
    //     { title: 'Cybersecurity Basics', path: 'subjects/data-computing/cybersecurity-basics/cybersecurity-basics.md' },
    //   ],
    // },
    {
      id: 'engineering',
      title: 'Engineering',
      children: [
        { title: 'Statics', path: 'subjects/engineering/statics/statics.md' },
        { title: 'Dynamics', path: 'subjects/engineering/dynamics/dynamics.md' },
        { title: 'Mechanics of Materials', path: 'subjects/engineering/mechanics-of-materials/mechanics-of-materials.md' },
        { title: 'Fluid Mechanics', path: 'subjects/engineering/fluid-mechanics/fluid-mechanics.md' },
        { title: 'Heat Transfer', path: 'subjects/engineering/heat-transfer/heat-transfer.md' },
        { title: 'Materials Science', path: 'subjects/engineering/materials-science/materials-science.md' },
        { title: 'Electrical Circuit Analysis', path: 'subjects/engineering/electrical-circuit-analysis/electrical-circuit-analysis.md' },
        { title: 'Linear System Signal Analysis', path: 'subjects/engineering/linear-system-signal-analysis/linear-system-signal-analysis.md' },
        { title: 'Electronics', path: 'subjects/engineering/electronics/electronics.md' },
        { title: 'Signals and Systems', path: 'subjects/engineering/signals-and-systems/signals-and-systems.md' },
        { title: 'Control Systems', path: 'subjects/engineering/control-systems/control-systems.md' },
        { title: 'Instrumentation', path: 'subjects/engineering/instrumentation/instrumentation.md' },
        { title: 'CAD', path: 'subjects/engineering/cad/cad.md' },
        { title: 'Simulation', path: 'subjects/engineering/simulation/simulation.md' },
        { title: 'Manufacturing', path: 'subjects/engineering/manufacturing/manufacturing.md' },
        { title: 'Quality Control', path: 'subjects/engineering/quality-control/quality-control.md' },
        { title: 'Project Management', path: 'subjects/engineering/project-management/project-management.md' },
        { title: 'Cost/Risk Analysis', path: 'subjects/engineering/cost-risk-analysis/cost-risk-analysis.md' },
        { title: 'Kinematics', path: 'subjects/engineering/kinematics/kinematics.md' },
      ],
    },
    {
      id: 'medical-biology',
      title: 'Medical / Biology',
      children: [
        // { title: 'General Biology', path: 'subjects/medical-biology/general-biology/general-biology.md' },
        { title: 'General Chemistry', path: 'subjects/medical-biology/general-chemistry/general-chemistry.md' },
        { title: 'Organic Chemistry', path: 'subjects/medical-biology/organic-chemistry/organic-chemistry.md' },
        // { title: 'Biochemistry', path: 'subjects/medical-biology/biochemistry/biochemistry.md' },
        // { title: 'Anatomy', path: 'subjects/medical-biology/anatomy/anatomy.md' },
        // { title: 'Physiology', path: 'subjects/medical-biology/physiology/physiology.md' },
        // { title: 'Genetics', path: 'subjects/medical-biology/genetics/genetics.md' },
        // { title: 'Psychology', path: 'subjects/medical-biology/psychology/psychology.md' },
        // { title: 'Ethics', path: 'subjects/medical-biology/ethics/ethics.md' },
        // { title: 'Lab Safety', path: 'subjects/medical-biology/lab-safety/lab-safety.md' },
        // { title: 'Scientific Writing', path: 'subjects/medical-biology/scientific-writing/scientific-writing.md' },
      ],
    },
  ],
};
