window.UES_GUIDE_MANIFEST = (() => {
  const note = (title, path) => ({ title, path });
  const structure = (id, title, children) => ({ id, title, children });

  return {
    structures: [
      structure('general', 'General', [
        note('Introduction', 'subjects/general/introduction.md'),
        note('Adding and Editing Documents', 'subjects/general/adding-and-editing-documents.md'),
      ]),
      structure('math', 'Math', [
        note('Arithmetic', 'subjects/math/arithmetic.md'),
        note('Logic', 'subjects/math/logic.md'),
        note('Geometry', 'subjects/math/geometry.md'),
        note('Algebra', 'subjects/math/algebra.md'),
        note('Functions', 'subjects/math/functions.md'),
        note('Probability', 'subjects/math/probability.md'),
        note('Statistics', 'subjects/math/statistics.md'),
        note('Trigonometry', 'subjects/math/trigonometry.md'),
        note('Limits', 'subjects/math/limits.md'),
        note('Derivatives', 'subjects/math/derivatives.md'),
        note('Integrals', 'subjects/math/integrals.md'),
        note('Series', 'subjects/math/series.md'),
        note('Vectors', 'subjects/math/vectors.md'),
        note('Matrices', 'subjects/math/matrices.md'),
        note('Eigenvalues', 'subjects/math/eigenvalues.md'),
        note('Discrete Math', 'subjects/math/discrete-math.md'),
        note('Modeling', 'subjects/math/modeling.md'),
        note('First Order ODEs', 'subjects/math/first-order-odes.md'),
        note('Second Order ODEs', 'subjects/math/second-order-odes.md'),
        note('Systems of ODEs', 'subjects/math/systems-of-odes.md'),
        note('Proof Writing', 'subjects/math/proof-writing.md'),
      ]),
      structure('physics', 'Physics', [
        note('Thermodynamics I', 'subjects/physics/thermodynamics-i.md'),
        note('Physics I', 'subjects/physics/physics-i.md'),
        note('Physics II', 'subjects/physics/physics-ii.md'),
        note('Quantum Physics I', 'subjects/physics/quantum-physics-i.md'),
        note('Classical Mechanics', 'subjects/physics/classical-mechanics.md'),
        note('Electricity and Magnetism', 'subjects/physics/electricity-and-magnetism.md'),
        note('Relativity', 'subjects/physics/relativity.md'),
        note('Optics', 'subjects/physics/optics.md'),
        note('Computational Physics', 'subjects/physics/computational-physics.md'),
        note('Lab and Measurement', 'subjects/physics/lab-and-measurement.md'),
        note('Astrophysics and Cosmology', 'subjects/physics/astrophysics-and-cosmology.md'),
        note('Biophysics', 'subjects/physics/biophysics.md'),
        note('Condensed Matter Physics', 'subjects/physics/condensed-matter-physics.md'),
        note('Geophysics', 'subjects/physics/geophysics.md'),
        note('Particle and Nuclear Physics', 'subjects/physics/particle-and-nuclear-physics.md'),
        note('Plasma Physics', 'subjects/physics/plasma-physics.md'),
      ]),
      structure('data-computing', 'Data / Computing', [
        note('Programming', 'subjects/data-computing/programming.md'),
        note('Data Structures', 'subjects/data-computing/data-structures.md'),
        note('Algorithms', 'subjects/data-computing/algorithms.md'),
        note('Databases', 'subjects/data-computing/databases.md'),
        note('Software Design', 'subjects/data-computing/software-design.md'),
        note('Version Control', 'subjects/data-computing/version-control.md'),
        note('Operating Systems', 'subjects/data-computing/operating-systems.md'),
        note('Computer Architecture', 'subjects/data-computing/computer-architecture.md'),
        note('Networking', 'subjects/data-computing/networking.md'),
        note('Cybersecurity Basics', 'subjects/data-computing/cybersecurity-basics.md'),
      ]),
      structure('engineering', 'Engineering', [
        note('Statics', 'subjects/engineering/statics.md'),
        note('Dynamics', 'subjects/engineering/dynamics.md'),
        note('Mechanics of Materials', 'subjects/engineering/mechanics-of-materials.md'),
        note('Fluid Mechanics', 'subjects/engineering/fluid-mechanics.md'),
        note('Heat Transfer', 'subjects/engineering/heat-transfer.md'),
        note('Materials Science', 'subjects/engineering/materials-science.md'),
        note('Electrical Circuit Analysis', 'subjects/engineering/electrical-circuit-analysis.md'),
        note('Linear System Signal Analysis', 'subjects/engineering/linear-system-signal-analysis.md'),
        note('Electronics', 'subjects/engineering/electronics.md'),
        note('Signals and Systems', 'subjects/engineering/signals-and-systems.md'),
        note('Control Systems', 'subjects/engineering/control-systems.md'),
        note('Instrumentation', 'subjects/engineering/instrumentation.md'),
        note('CAD', 'subjects/engineering/cad.md'),
        note('Simulation', 'subjects/engineering/simulation.md'),
        note('Manufacturing', 'subjects/engineering/manufacturing.md'),
        note('Quality Control', 'subjects/engineering/quality-control.md'),
        note('Project Management', 'subjects/engineering/project-management.md'),
        note('Cost/Risk Analysis', 'subjects/engineering/cost-risk-analysis.md'),
        note('Kinematics', 'subjects/engineering/kinematics.md'),
      ]),
      structure('medical-biology', 'Medical / Biology', [
        note('General Biology', 'subjects/medical-biology/general-biology.md'),
        note('General Chemistry', 'subjects/medical-biology/general-chemistry.md'),
        note('Organic Chemistry', 'subjects/medical-biology/organic-chemistry.md'),
        note('Biochemistry', 'subjects/medical-biology/biochemistry.md'),
        note('Anatomy', 'subjects/medical-biology/anatomy.md'),
        note('Physiology', 'subjects/medical-biology/physiology.md'),
        note('Genetics', 'subjects/medical-biology/genetics.md'),
        note('Psychology', 'subjects/medical-biology/psychology.md'),
        note('Ethics', 'subjects/medical-biology/ethics.md'),
        note('Lab Safety', 'subjects/medical-biology/lab-safety.md'),
        note('Scientific Writing', 'subjects/medical-biology/scientific-writing.md'),
      ]),
    ],
  };
})();
